export default {
  kind: 'collectionType',
  collectionName: 'stripe_prices',
  info: {
    singularName: 'stripe-price',
    pluralName: 'stripe-prices',
    displayName: 'Stripe Prices',
  },
  options: {
    draftAndPublish: false,
  },
  pluginOptions: {},
  attributes: {
    stripePriceId: {
      type: 'string',
      required: true,
      unique: true,
    },
    stripeProduct: {
      type: 'relation',
      relation: 'manyToOne',
      target: 'plugin::stripe-strapi-plugin.stripe-product',
      inversedBy: 'stripePrices',
      required: true,
    },
    active: {
      type: 'boolean',
      required: true,
      default: true,
    },
    billingScheme: {
      type: 'enumeration',
      enum: ['per_unit', 'tiered'],
      default: 'per_unit',
      required: true,
    },
    created: {
      type: 'biginteger',
    },
    currency: {
      type: 'enumeration',
      required: true,
      enum: [
        'USD',
        'AED',
        'AFN',
        'ALL',
        'AMD',
        'ANG',
        'AOA',
        'ARS',
        'AUD',
        'AWG',
        'AZN',
        'BAM',
        'BBD',
        'BDT',
        'BGN',
        'BIF',
        'BMD',
        'BND',
        'BOB',
        'BRL',
        'BSD',
        'BWP',
        'BYN',
        'BZD',
        'CAD',
        'CDF',
        'CHF',
        'CLP',
        'CNY',
        'COP',
        'CRC',
        'CVE',
        'CZK',
        'DJF',
        'DKK',
        'DOP',
        'DZD',
        'EGP',
        'ETB',
        'EUR',
        'FJD',
        'FKP',
        'GBP',
        'GEL',
        'GIP',
        'GMD',
        'GNF',
        'GTQ',
        'GYD',
        'HKD',
        'HNL',
        'HTG',
        'HUF',
        'IDR',
        'ILS',
        'INR',
        'ISK',
        'JMD',
        'JPY',
        'KES',
        'KGS',
        'KHR',
        'KMF',
        'KRW',
        'KYD',
        'KZT',
        'LAK',
        'LBP',
        'LKR',
        'LRD',
        'LSL',
        'MAD',
        'MDL',
        'MGA',
        'MKD',
        'MMK',
        'MNT',
        'MOP',
        'MUR',
        'MVR',
        'MWK',
        'MXN',
        'MYR',
        'MZN',
        'NAD',
        'NGN',
        'NIO',
        'NOK',
        'NPR',
        'NZD',
        'PAB',
        'PEN',
        'PGK',
        'PHP',
        'PKR',
        'PLN',
        'PYG',
        'QAR',
        'RON',
        'RSD',
        'RUB',
        'RWF',
        'SAR',
        'SBD',
        'SCR',
        'SEK',
        'SGD',
        'SHP',
        'SLE',
        'SOS',
        'SRD',
        'STD',
        'SZL',
        'THB',
        'TJS',
        'TOP',
        'TRY',
        'TTD',
        'TWD',
        'TZS',
        'UAH',
        'UGX',
        'UYU',
        'UZS',
        'VND',
        'VUV',
        'WST',
        'XAF',
        'XCD',
        'XCG',
        'XOF',
        'XPF',
        'YER',
        'ZAR',
        'ZMW',
      ],
    },
    customUnitAmount: {
      type: 'component',
      component: 'stripe.price-custom-unit-amount',
    },
    livemode: {
      type: 'boolean',
    },
    lookupKey: {
      type: 'string',
    },
    metadata: {
      type: 'component',
      component: 'component.key-value-pairs',
      repeatable: true,
    },
    nickname: {
      type: 'string',
    },
    recurring: {
      type: 'component',
      component: 'stripe.price-recurring',
      repeatable: false,
    },
    taxBehavior: {
      type: 'enumeration',
      enum: ['inclusive', 'exclusive', 'unspecified'],
    },
    tiers: {
      type: 'component',
      component: 'stripe.price-tier',
      repeatable: true,
    },
    tiersMode: {
      type: 'enumeration',
      enum: ['graduated', 'volume'],
    },
    type: {
      type: 'enumeration',
      enum: ['one_time', 'recurring'],
      required: true,
    },
    unitAmount: {
      type: 'integer',
    },
    unitAmountDecimal: {
      type: 'string',
    },
  },
};
